### tạo tài khoản admin khởi tạo
POST http://localhost:8000/account/create/admin/init
Content-Type: application/json

{
    "email": "admin1",
    "name": "beerus",
    "password": "123456",
    "sex": "1",
    "phone": "0123456789",
    "address": "97 Man Thiện"
}

### tạo tài khoản thường
POST http://localhost:8000/account/signup
Content-Type: application/json

{
    "email": "user12",
    "name": "beerus",
    "password": "123456",
    "sex": "1",
    "phone": "0123456789",
    "address": "97 Man Thiện"
}

### Tạo tài khoản stocker
POST http://localhost:8000/account/create/stocker
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMzMxNjc4MiwiZXhwIjoxNjMzMzUyNzgyfQ.8a5Z7yYMa50z82HUY-bv1qw1v9MvxFNngt6wiDRZUbc
Content-Type: application/json

{
    "email": "stocker3",
    "name": "beerus",
    "password": "123456",
    "sex": "1",
    "phone": "0123456789",
    "address": "97 Man Thiện"
}

### Tạo tài khoản admin
POST http://localhost:8000/account/create/admin
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMzMxNjc4MiwiZXhwIjoxNjMzMzUyNzgyfQ.8a5Z7yYMa50z82HUY-bv1qw1v9MvxFNngt6wiDRZUbc
Content-Type: application/json

{
    "email": "admin3",
    "name": "beerus",
    "password": "123456",
    "sex": "1",
    "phone": "0123456789",
    "address": "97 Man Thiện"
}

### Đăng nhập
POST http://localhost:8000/account/login
Content-Type: application/json

{
    "email": "sieuquaytihon80@gmail.com",
    "password": "123456"
}

### đăng nhập quản lý
POST http://localhost:8000/account/login/personel
Content-Type: application/json

{
    "email": "stocker3",
    "password": "123456"
}

### Quên mật khẩu
POST http://localhost:8000/account/forgot-password
Content-Type: application/json

{
    "email": "sieuquaytihon80@gmail.com"
}


### Xác nhận mã
POST http://localhost:8000/account/confirm
Content-Type: application/json

{
    "code": "853456",
    "id_account": "8"
}

### Lấy thông tin tài khoản của mình
GET http://localhost:8000/account/information
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMzMxNjc4MiwiZXhwIjoxNjMzMzUyNzgyfQ.8a5Z7yYMa50z82HUY-bv1qw1v9MvxFNngt6wiDRZUbc

### Danh sách tài khoản
GET http://localhost:8000/account/all
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMzMxNjc4MiwiZXhwIjoxNjMzMzUyNzgyfQ.8a5Z7yYMa50z82HUY-bv1qw1v9MvxFNngt6wiDRZUbc

### số lượng tài khoản trong danh sách
GET http://localhost:8000/account/all/amount
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMzA1ODg3MiwiZXhwIjoxNjMzMDYyNDcyfQ.jLV7z2oTNTXcyQcZUL3jiKHSbRMSTUYCK5SECHDiMm0

### Danh sách tài khoản bị khóa
GET http://localhost:8000/account/lock
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMjgzOTgxOSwiZXhwIjoxNjMyODQzNDE5fQ.0qqDNgfVUwJmDFPUNTn6EW9JDr0wZNpw2sHfdlGCis0

### Số lượng tài khoản bị khóa
GET http://localhost:8000/account/lock/amount
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMjgzOTgxOSwiZXhwIjoxNjMyODQzNDE5fQ.0qqDNgfVUwJmDFPUNTn6EW9JDr0wZNpw2sHfdlGCis0

### Tìm kiếm tài khoản theo email
GET http://localhost:8000/account/search
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMjgzOTgxOSwiZXhwIjoxNjMyODQzNDE5fQ.0qqDNgfVUwJmDFPUNTn6EW9JDr0wZNpw2sHfdlGCis0
Content-Type: application/json

{
    "search": "test",
    "page": "1"
}

### Số lượng kết quả tìm theo email
GET http://localhost:8000/account/search/amount
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMjgzOTgxOSwiZXhwIjoxNjMyODQzNDE5fQ.0qqDNgfVUwJmDFPUNTn6EW9JDr0wZNpw2sHfdlGCis0
Content-Type: application/json

{
    "search": "p"
}

### Đổi password
PUT http://localhost:8000/account/change_password
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMjg0MTM5NCwiZXhwIjoxNjMyODQ0OTk0fQ.6SHyRJdjI-v2eAI0tHkm7O-VKz0ShXvRsfSVu0Ajo0k
Content-Type: application/json

{
    "new_password": "123456",
    "id_account": 2
}

### khóa tài khoản
PUT http://localhost:8000/account/lock
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMjg0MTM5NCwiZXhwIjoxNjMyODQ0OTk0fQ.6SHyRJdjI-v2eAI0tHkm7O-VKz0ShXvRsfSVu0Ajo0k
Content-Type: application/json

{
    "id_account": "2"
}

### mở tài khoản bị khóa
PUT http://localhost:8000/account/unlock
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMjg0MTM5NCwiZXhwIjoxNjMyODQ0OTk0fQ.6SHyRJdjI-v2eAI0tHkm7O-VKz0ShXvRsfSVu0Ajo0k
Content-Type: application/json

{
    "id_account": "2"
}

### cập nhật tài khoản
PUT http://localhost:8000/account/update/information
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjozLCJwb3NpdGlvbiI6MCwiZW1haWwiOiJzaWV1cXVheXRpaG9uODBAZ21haWwuY29tIiwic3RhdHVzIjoxLCJpYXQiOjE2MzMzMTc3MTksImV4cCI6MTYzMzM1MzcxOX0.0w8g8O0Fq37GsXRQPxgHir6X4aXNopufk7i40zmq9L0
Content-Type: application/json

{
    "name": "Phạm Hoàng Long",
    "sex": "1",
    "phone": "0123456789",
    "address": "97 Man Thiện, phường Hiệp Phú, Quận Thủ Đức, thành phố Hồ Chí Minh"
}