### thêm 1 sản phẩm vô giỏ hàng
POST   http://localhost:8000/cart/product/9
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo5LCJwb3NpdGlvbiI6MCwiZW1haWwiOiJ1c2VyMSIsInN0YXR1cyI6MSwiaWF0IjoxNjMzNDAyNTcyLCJleHAiOjE2MzM0Mzg1NzJ9.oKKz7lCHWM0ya4V_SDJZ1BTMg8CAVTDCgotbFVGOrIs

### lấy tất cả sản phẩm trong giỏ hàng
GET  http://localhost:8000/cart/account
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo5LCJwb3NpdGlvbiI6MCwiZW1haWwiOiJ1c2VyMSIsInN0YXR1cyI6MSwiaWF0IjoxNjMzNDAyNTcyLCJleHAiOjE2MzM0Mzg1NzJ9.oKKz7lCHWM0ya4V_SDJZ1BTMg8CAVTDCgotbFVGOrIs

### Sửa số lượng của 1 sản phẩm
PUT http://localhost:8000/cart/update/1/quantity?new_quantity=2
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMzI1MzAwOCwiZXhwIjoxNjMzMjg5MDA4fQ.QvbHJMMu1KaumcrBN3e34-Qw9lMLtTfDMgH5S-Qe5B8

### xóa sản phẩm trong giỏ hàng
DELETE  http://localhost:8000/cart/product/14
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo1LCJwb3NpdGlvbiI6MiwiZW1haWwiOiJhZG1pbjEiLCJzdGF0dXMiOjEsImlhdCI6MTYzMzI1MzAwOCwiZXhwIjoxNjMzMjg5MDA4fQ.QvbHJMMu1KaumcrBN3e34-Qw9lMLtTfDMgH5S-Qe5B8